project_id = "lyhpskhheiamtskkbfes"

[functions.send-verification]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false